.TH DHCP-STATS 1
.SH NAME
dhcp-stats \- obtain statistics on the load of subnets
.SH SYNOPSIS
.B dhcp-stats
[\fB\-i\fR \fI<interface>\fR]
[\fB\-r\fR \fI<filename>\fR]
.IR <ip-prefix>
[<ip-prefix>[...]]
.SH DESCRIPTION
.B dhcp-stats
generates statistics that includes details about subnet loads based on gathered data from a pcap file or captured traffic on an interface.
.SH OPTIONS
.TP
.BR \-i " " \fI<interface>\fR
Interface for live capture.
.TP
.BR \-r " " \fI<filename>\fR
Generated PCAP file.